// Code generated by protoc-gen-go.
// source: proto/sec.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/sec.proto

It has these top-level messages:
	Message
	Record
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

type Message struct {
	Header    []byte `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Protected []byte `protobuf:"bytes,2,opt,name=protected,proto3" json:"protected,omitempty"`
	Payload   []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto1.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Record struct {
	Index int32  `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// Serialized 'Message', AES-128-GCM encrypted using the initial message's signature
	// nonce = "0 (32 bits), 0 (32-bits, big endian) index (32-bit, big endian)"
	// tag is appended.
	EncryptedMessage []byte `protobuf:"bytes,3,opt,name=encrypted_message,proto3" json:"encrypted_message,omitempty"`
	// Serialized 'Message', AES-128-GCM encrypted using the initial message's signature
	// nonce = "0 (32 bits), 1 (32-bits, big endian) index (32-bit, big endian)"
	// tag is appended.
	EncryptedAudit []byte `protobuf:"bytes,5,opt,name=encrypted_audit,proto3" json:"encrypted_audit,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto1.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*Message)(nil), "proto.Message")
	proto1.RegisterType((*Record)(nil), "proto.Record")
}

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0x8e, 0xb1, 0xca, 0xc2, 0x30,
	0x14, 0x85, 0xe9, 0xff, 0x37, 0x2d, 0xbd, 0x54, 0x4b, 0xb3, 0x18, 0x37, 0xe9, 0xe4, 0xa4, 0x83,
	0xcf, 0x21, 0x88, 0x9b, 0x93, 0xc4, 0xe4, 0x50, 0x0b, 0xda, 0x84, 0x24, 0x05, 0xfb, 0xf6, 0xda,
	0xa8, 0x38, 0xdd, 0xcb, 0x39, 0x87, 0x8f, 0x8f, 0x2a, 0xeb, 0x4c, 0x30, 0x5b, 0x0f, 0xb5, 0x89,
	0x1f, 0x67, 0xf1, 0x34, 0x07, 0xca, 0xf7, 0xf0, 0x5e, 0xb6, 0xe0, 0x73, 0xca, 0xae, 0x90, 0x1a,
	0x4e, 0x24, 0xab, 0x64, 0x5d, 0xf2, 0x9a, 0x8a, 0x69, 0x03, 0x15, 0xa0, 0xc5, 0x5f, 0x8c, 0x2a,
	0xca, 0xad, 0x1c, 0x6f, 0x46, 0x6a, 0xf1, 0xff, 0xdd, 0xf8, 0xae, 0xed, 0x65, 0x18, 0x1c, 0x44,
	0x3a, 0x45, 0xcd, 0x89, 0xb2, 0x23, 0x94, 0x71, 0x9a, 0xcf, 0x88, 0x75, 0xbd, 0xc6, 0x23, 0xf2,
	0x18, 0x2f, 0x29, 0x0d, 0xa3, 0x45, 0x44, 0x15, 0x7c, 0x49, 0x35, 0x7a, 0xe5, 0x46, 0xfb, 0xa2,
	0x9f, 0xef, 0x6f, 0x85, 0x0f, 0x74, 0x41, 0xd5, 0xaf, 0x92, 0x83, 0xee, 0x82, 0x60, 0x53, 0x71,
	0xc9, 0xa2, 0xf3, 0xee, 0x19, 0x00, 0x00, 0xff, 0xff, 0x31, 0x86, 0x08, 0x3a, 0xcd, 0x00, 0x00,
	0x00,
}
